### ISSUE TITLE
It works, but some errors have appeared

### ISSUE THREAD

**Issue by ViesLink** [tannerbohn/MindMap#1]
1# When I move the mouse over the gui interface，the following errors continue to appear 。

''Exception in thread Thread-187:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "MindMap-master\Thought.py", line 943, in pulse
    self.moveByPix((0,-1.0*pixMove*dt))
  File "MindMap-master\Thought.py", line 621, in moveByPix
    self.reDraw()
  File "MindMap-master\Thought.py", line 220, in reDraw
    self.canvas.coords(self.mainRingIndex, x0p, y0p, x1p, y1p)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 2299, in coords
    self.tk.call((self._w, 'coords') + args)))
ValueError: could not convert string to float: expected

Exception in thread Thread-211:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "MindMap-master\Thought.py", line 943, in pulse
    self.moveByPix((0,-1.0*pixMove*dt))
  File "MindMap-master\Thought.py", line 617, in moveByPix
    pixelY=self.root.winfo_height()
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 844, in winfo_height
    self.tk.call('winfo', 'height', self._w))
ValueError: invalid literal for int() with base 10: 'expected boolean value but got "??"'

Exception in thread Thread-219......''

2# Is it possible to do some anti-aliasing optimization?

**Comment by tannerbohn** [comment]
Unfortunately, this code was written while I was still quite inexperienced. Ideally, the code would be re-written with something more efficient than tkinter (which is more suitable for simple interfaces than for many many visual objects and animation). Maintaining this code is currently very low priority.

**Comment by ViesLink** [comment]
Fine ,but this project really brought me some inspiration.
I'm using mindmaps-master (based on JavaScript) now.
Thanks for your reply.
